name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      RUSTC_WRAPPER: ""
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux
            exe_suffix: ""
          - os: macos-latest
            artifact_name: macos
            exe_suffix: ""
          - os: windows-latest
            artifact_name: windows
            exe_suffix: ".exe"

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: cargo check
        run: cargo check --workspace --all-targets --locked

      - name: cargo test
        run: cargo test --workspace --locked

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo build release
        run: cargo build --release --package arkama --bins --locked

      - name: upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arkama-${{ matrix.artifact_name }}
          path: |
            target/release/arkama${{ matrix.exe_suffix }}
            target/release/arkama-cli${{ matrix.exe_suffix }}
